language: minimal

git:
  quiet: true

os: linux

env: GAME_NAME="KAG Rewritten" GODOT_VERSION="3.2"

before_install:
- echo 'keystore/release_user="${ANDROID_RELEASE_USER}"' >> src/export_presets.cfg
- echo 'keystore/release_password="${ANDROID_RELEASE_PASSWORD}"' >> src/export_presets.cfg

install:
- sudo apt-get update
- sudo apt-get install -y --no-install-recommends ca-certificates openjdk-8-jdk
- sudo rm -rf /var/lib/apt/lists/*
- wget -q "https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip"
- wget -q "https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz"
- mkdir -p ~/.cache
- mkdir -p ~/.config/godot
- mkdir -p ~/.local/share/godot/templates/${GODOT_VERSION}.stable
- unzip Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip
- unzip Godot_v${GODOT_VERSION}-stable_export_templates.tpz
- sudo mv Godot_v${GODOT_VERSION}-stable_linux_headless.64 /usr/local/bin/godot
- mv templates/* ~/.local/share/godot/templates/${GODOT_VERSION}.stable
- godot -e -q
- sudo mkdir -p /home/android
- cd /home/android
- echo "Installing Android dependencies"
- sudo wget -q "https://dl.google.com/android/repository/platform-tools-latest-linux.zip"
- sudo unzip -q platform-tools-latest-linux.zip
- sudo rm platform-tools-latest-linux.zip
- echo 'export/android/adb = "/home/android/platform-tools/adb"' >> ~/.config/godot/editor_settings-3.tres
- echo 'export/android/jarsigner = "/usr/lib/jvm/java-8-openjdk-amd64/bin/jarsigner"' >> ~/.config/godot/editor_settings-3.tres
- echo 'export/android/force_system_user = false' >> ~/.config/godot/editor_settings-3.tres
- echo 'export/android/timestamping_authority_url = ""' >> ~/.config/godot/editor_settings-3.tres
- echo 'export/android/shutdown_adb_on_exit = true' >> ~/.config/godot/editor_settings-3.tres
- cat ~/.config/godot/editor_settings-3.tres

script:
- cd ${TRAVIS_BUILD_DIR}
- mkdir -p "build/android"
- mkdir -p "build/windows"
- mkdir -p "build/linux"
- mkdir -p "build/mac"
- mkdir -p "build/html5"
- cd src
# Desktop
- sudo godot --export "Android" "../build/android/${GAME_NAME}-android.apk"
- sudo godot --export "Windows" "../build/windows/${GAME_NAME}.exe"
- sudo godot --export "Linux" "../build/linux/${GAME_NAME}"
- sudo godot --export "Mac" "../build/mac/${GAME_NAME}-mac.zip"
# Web
- sudo godot --export "Web" "../build/html5/index.html"
- cd ..

before_deploy:
- cp -R build/android/* .
- md5sum "${GAME_NAME}-android.apk" > "${GAME_NAME}-android-md5.txt"
# Only copying needed, exporting for Mac outputs a zip
- cp -R build/mac/* .
- md5sum "${GAME_NAME}-mac.zip" > "${GAME_NAME}-mac-md5.txt"
- zip -jr "${GAME_NAME}-linux.zip" build/linux
- md5sum "${GAME_NAME}-linux.zip" > "${GAME_NAME}-linux-md5.txt"
- zip -jr "${GAME_NAME}-windows.zip" build/windows
- md5sum "${GAME_NAME}-windows.zip" > "${GAME_NAME}-windows-md5.txt"
- zip -jr "${GAME_NAME}-html.zip" build/html5
- md5sum "${GAME_NAME}-html.zip" > "${GAME_NAME}-html-md5.txt"

deploy:
- provider: releases
  skip_cleanup: true
  token: $GITHUB_TOKEN
  file:
    - "${GAME_NAME}-android.apk"
    - "${GAME_NAME}-android-md5.txt"
    - "${GAME_NAME}-mac.zip"
    - "${GAME_NAME}-mac-md5.txt"
    - "${GAME_NAME}-linux.zip"
    - "${GAME_NAME}-linux-md5.txt"
    - "${GAME_NAME}-windows.zip"
    - "${GAME_NAME}-windows-md5.txt"
    - "${GAME_NAME}-html.zip"
    - "${GAME_NAME}-html-md5.txt"
  on:
    all_branches: true
    tags: true

- provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build/html5
  on:
    branch: master
#   tags: true

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL
